spring.application.name=notification-service
server.port=9040
server.servlet.context-path=/notifications


spring.datasource.url=jdbc:postgresql://localhost:5432/notification-service-DB
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update


eureka.client.service-url.defaultZone=http://localhost:8761/eureka