spring.application.name=user-service

server.port=9020

server.servlet.context-path=/users

jwt.secretKey=bcdsyvty32ugbjhdsvytcguqibYGYGYH76GYV$CTGVJSAJchsvhfdvhbshben-=vvs

spring.datasource.url=jdbc:postgresql://localhost:5432/user-service-DB
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

