
server.port=9020
spring.application.name=user-service

jwt.secretKey=bcdsyvty32ugbjhdsvytcguqibYGYGYH76GYV$CTGVJSAJchsvhfdvhbshben-=vvs

spring.datasource.url=jdbc:postgresql://localhost:5432/user-service
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

